server.port=9090

# Telegram API
telegram.api.url=https://api.telegram.org
telegram.bot.id=8612484633:AAH2F6eMQr9QQ7kjy4iVSfSZqUK6eK_9U_A
telegram.chat.id=7075611940

#OpenWeatherMap
open.weather.api.url=https://api.openweathermap.org/data/2.5
open.weather.api.token=4187805ee7f57bf075f09446ff0d6e71

