server.port=9090
spring.profiles.active=local

# Telegram API
telegram.api.url=https://api.telegram.org
telegram.bot.id=CHANGE_ME
telegram.chat.id=CHANGE_ME

#OpenWeatherMap
open.weather.api.url=https://api.openweathermap.org/data/2.5
open.weather.api.token=CHANGE_ME

# Mistral AI
ai.api.url=https://api.mistral.ai/v1/chat/completions
ai.api.token=YOUR_MISTRAL_API_KEY_HERE
